### PR TITLE
Handle display of templates that don’t have a size

### PR DESCRIPTION
**Pull request by jameshilliard**

### CODE REVIEW

**Comment by jameshilliard** [comment]
It would appear not all templates have a size, this at least makes it so those don't completely break the display.

**Comment by bowyern** [comment]
A zero sized template will cause other problems.  Can you tell me anything more about the templates that are showing up without a size?

**Comment by jameshilliard** [comment]
This is the one causing problems, looks to be a systemvm
```
                        stdClass Object
(
    [id] => b9e59556-ea5d-11e6-8a8a-0015177509fc
    [name] => CentOS 5.5(64-bit) no GUI (KVM)
    [displaytext] => CentOS 5.5(64-bit) no GUI (KVM)
    [ispublic] => 1
    [created] => 2017-02-03T19:55:38-0500
    [isready] => 
    [passwordenabled] => 
    [format] => QCOW2
    [isfeatured] => 1
    [crossZones] => 1
    [ostypeid] => bb32ae92-ea5d-11e6-8a8a-0015177509fc
    [ostypename] => CentOS 5.5 (64-bit)
    [account] => system
    [zoneid] => ba09a418-c1e3-4bc6-8652-0676e66ac0b4
    [zonename] => tpa
    [templatetype] => BUILTIN
    [hypervisor] => KVM
    [domain] => ROOT
    [domainid] => b9cfad6d-ea5d-11e6-8a8a-0015177509fc
    [isextractable] => 1
    [checksum] => ed0e788280ff2912ea40f7f91ca7a249
    [sshkeyenabled] => 
    [isdynamicallyscalable] => 
    [tags] => Array
        (
        )

)
1 
```

**Comment by jameshilliard** [comment]
I added a check so that we display but ignore BUILTIN templates

**Pull request merged**
